replicaCount: 1

image:
  repository: anfedimo/devops-dev-sabana-backend
  pullPolicy: IfNotPresent
  tag: "4"

service:
  type: NodePort
  port: 80
  targetPort: 9000

resources: {}

imagePullSecrets:
  - name: acr-secret

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  cpuAverageUtilization: 60
